// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matchmaker_common.proto

#ifndef PROTOBUF_matchmaker_5fcommon_2eproto__INCLUDED
#define PROTOBUF_matchmaker_5fcommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_matchmaker_5fcommon_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
inline void InitDefaults() {
}
}  // namespace protobuf_matchmaker_5fcommon_2eproto

enum MatchType {
  MATCH_TYPE_RANKED = 0,
  MATCH_TYPE_COOP_BOTS = 1,
  MATCH_TYPE_TEAM_RANKED = 2,
  MATCH_TYPE_SOLO_QUEUE = 3
};
bool MatchType_IsValid(int value);
const MatchType MatchType_MIN = MATCH_TYPE_RANKED;
const MatchType MatchType_MAX = MATCH_TYPE_SOLO_QUEUE;
const int MatchType_ARRAYSIZE = MatchType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MatchType_descriptor();
inline const ::std::string& MatchType_Name(MatchType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MatchType_descriptor(), value);
}
inline bool MatchType_Parse(
    const ::std::string& name, MatchType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MatchType>(
    MatchType_descriptor(), name, value);
}
enum DOTABotDifficulty {
  BOT_DIFFICULTY_PASSIVE = 0,
  BOT_DIFFICULTY_EASY = 1,
  BOT_DIFFICULTY_MEDIUM = 2,
  BOT_DIFFICULTY_HARD = 3,
  BOT_DIFFICULTY_UNFAIR = 4,
  BOT_DIFFICULTY_INVALID = 5
};
bool DOTABotDifficulty_IsValid(int value);
const DOTABotDifficulty DOTABotDifficulty_MIN = BOT_DIFFICULTY_PASSIVE;
const DOTABotDifficulty DOTABotDifficulty_MAX = BOT_DIFFICULTY_INVALID;
const int DOTABotDifficulty_ARRAYSIZE = DOTABotDifficulty_MAX + 1;

const ::google::protobuf::EnumDescriptor* DOTABotDifficulty_descriptor();
inline const ::std::string& DOTABotDifficulty_Name(DOTABotDifficulty value) {
  return ::google::protobuf::internal::NameOfEnum(
    DOTABotDifficulty_descriptor(), value);
}
inline bool DOTABotDifficulty_Parse(
    const ::std::string& name, DOTABotDifficulty* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DOTABotDifficulty>(
    DOTABotDifficulty_descriptor(), name, value);
}
enum MatchLanguages {
  MATCH_LANGUAGE_ENGLISH = 1,
  MATCH_LANGUAGE_RUSSIAN = 2,
  MATCH_LANGUAGE_CHINESE = 3
};
bool MatchLanguages_IsValid(int value);
const MatchLanguages MatchLanguages_MIN = MATCH_LANGUAGE_ENGLISH;
const MatchLanguages MatchLanguages_MAX = MATCH_LANGUAGE_CHINESE;
const int MatchLanguages_ARRAYSIZE = MatchLanguages_MAX + 1;

const ::google::protobuf::EnumDescriptor* MatchLanguages_descriptor();
inline const ::std::string& MatchLanguages_Name(MatchLanguages value) {
  return ::google::protobuf::internal::NameOfEnum(
    MatchLanguages_descriptor(), value);
}
inline bool MatchLanguages_Parse(
    const ::std::string& name, MatchLanguages* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MatchLanguages>(
    MatchLanguages_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MatchType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MatchType>() {
  return ::MatchType_descriptor();
}
template <> struct is_proto_enum< ::DOTABotDifficulty> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DOTABotDifficulty>() {
  return ::DOTABotDifficulty_descriptor();
}
template <> struct is_proto_enum< ::MatchLanguages> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MatchLanguages>() {
  return ::MatchLanguages_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_matchmaker_5fcommon_2eproto__INCLUDED
